name: Build
on:
  push:
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build CSS and JSON
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build CSS & JSON
        run: npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: dist
          message: "chore(build): 🤖 Rebuild theme [${{ github.sha }}]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}